name: daniboard_examples
description: Examples
version: 0.0.1

environment:
  sdk: ^3.4.4

dependencies:
  daniboard:
    path: '../'

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0