name: daniboard
description: Non-flutter clipboard solution for dart cli applications
version: 1.0.1
repository: https://github.com/ikuruzum/daniboard

environment:
  sdk: ^3.0.0


dependencies:
   path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
